### ISSUE TITLE
QQ 登录页面作业反馈

### ISSUE THREAD

**Issue by twhy** [cdhqing/cdhqing.github.io#1]
总体不错，改进建议如下
1. `<img src="images/logo.png" width="244px">` `width` 属性处的 `px` 可以删除。
2. `.content-form-inp` 的圆角应该是 `4px`
3. 可以通过 `input::-webkit-input-placeholder { color: #aaa; }` 给 placeholder 设置颜色。
4. 两个按钮可以设置 `padding: 0` 去掉默认浏览器样式，这样按钮中的文字才会垂直居中。
5. `a:hover { color: red; }` 可以去掉。
6. `.logo` 的样式要调整成 
```
.logo {
  padding: 30px 0 20px;
}
```

**Comment by cdhqing** [comment]
已修改
